name: Update Spotify

on:
  schedule:
    - cron: '*/10 * * * *'  # Ejecuta cada 10 minutos
  workflow_dispatch:  # Permite ejecutarlo manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: kittinan/spotify-github-profile@main
        with:
          client_id: ${{ secrets.SPOTIFY_CLIENT_ID }}
          client_secret: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          refresh_token: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          readme_path: README.md
